apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: dvl1987
spec:
  containers:
  - image: busybox
    name: time-check
    command: [ "sh", "-c","while true; do date; sleep $TIME_FREQ; done > /opt/time/time-check.log"]
    envFrom:
    - configMapRef:
        name: time-config
    volumeMounts:
    - mountPath: /opt/time
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}